name: ci
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.22.6
      - name: Install deps
        run: |
          cd lib
          npm ci
      - name: Run tests
        run: |
          cd lib
          npm test